Repository aneoconsulting/ArmoniK.Infra, pull requests merged in 2023-06, with the labels that each got.

#18 ci: enhance workflow
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  armonik/README.md
  armonik/main.tf
  armonik/versions.tf
  container-registry/aws/ecr/versions.tf
  kubernetes/aws/eks/versions.tf
  monitoring/aws/cloudwatch-log-group/versions.tf
  monitoring/onpremise/exporters/node-exporter/outputs.tf
  monitoring/onpremise/keda/versions.tf
  monitoring/onpremise/metrics-server/versions.tf
  persistent-volume/aws/efs/versions.tf
  storage/aws/efs/versions.tf
  storage/aws/elasticache/versions.tf
  storage/aws/mq/versions.tf
  storage/aws/s3/versions.tf
  storage/onpremise/activemq/versions.tf
  storage/onpremise/minio/versions.tf
  storage/onpremise/mongodb/versions.tf
  storage/onpremise/redis/versions.tf
  utils/aws/credentials/versions.tf
  utils/aws/kms/versions.tf
  utils/default-images/main.tf
  utils/default-images/versions.tf
  utils/needed-storage/main.tf
  utils/needed-storage/versions.tf
Labels: ci

#19 ci: release
  .github/workflows/release.yml
Labels: ci

#20 refactor: update aws vpc module
  .gitignore
  networking/aws/vpc/README.md
  networking/aws/vpc/endpoints.tf
  networking/aws/vpc/examples/README.md
  networking/aws/vpc/examples/complete/README.md
  networking/aws/vpc/examples/complete/main.tf
  networking/aws/vpc/examples/complete/outputs.tf
  networking/aws/vpc/examples/complete/variables.tf
  networking/aws/vpc/examples/complete/versions.tf
  networking/aws/vpc/examples/simple/README.md
  networking/aws/vpc/examples/simple/main.tf
  networking/aws/vpc/examples/simple/outputs.tf
  networking/aws/vpc/examples/simple/variables.tf
  networking/aws/vpc/examples/simple/versions.tf
  networking/aws/vpc/locals.tf
  networking/aws/vpc/main.tf
  networking/aws/vpc/outputs.tf
  networking/aws/vpc/peering.tf
  networking/aws/vpc/security-groups.tf
  networking/aws/vpc/variables.tf
  networking/aws/vpc/versions.tf
Labels: enhancement

#21 fix: Update documentation workflow
  .github/workflows/documentation.yml
  container-registry/aws/ecr/README.md
  kubernetes/aws/eks/README.md
  monitoring/aws/cloudwatch-log-group/README.md
  monitoring/onpremise/keda/README.md
  monitoring/onpremise/metrics-server/README.md
  networking/aws/vpc/README.md
  networking/aws/vpc/examples/complete/README.md
  networking/aws/vpc/examples/simple/README.md
  persistent-volume/aws/efs/README.md
  storage/aws/efs/README.md
  storage/aws/elasticache/README.md
  storage/aws/mq/README.md
  storage/aws/mq/outputs.tf
  storage/aws/s3/README.md
  storage/onpremise/activemq/README.md
  storage/onpremise/minio/README.md
  storage/onpremise/mongodb/README.md
  storage/onpremise/redis/README.md
  utils/aws/credentials/README.md
  utils/aws/kms/README.md
  utils/default-images/README.md
  utils/needed-storage/README.md
Labels: ci

#22 feat: include onprem cluster depl modules in new infra infra v2
  kubernetes/onpremise/kubeadm/1-install-master.tf
  kubernetes/onpremise/kubeadm/2-install-workers.tf
  kubernetes/onpremise/kubeadm/README.md
  kubernetes/onpremise/kubeadm/exemples/README.md
  kubernetes/onpremise/kubeadm/exemples/complete/README.md
  kubernetes/onpremise/kubeadm/exemples/complete/main.tf
  kubernetes/onpremise/kubeadm/exemples/complete/outputs.tf
  kubernetes/onpremise/kubeadm/exemples/complete/variables.tf
  kubernetes/onpremise/kubeadm/exemples/complete/versions.tf
  kubernetes/onpremise/kubeadm/main.tf
  kubernetes/onpremise/kubeadm/outputs.tf
  kubernetes/onpremise/kubeadm/scripts/install_docker.sh
  kubernetes/onpremise/kubeadm/scripts/install_kubernetes.sh
  kubernetes/onpremise/kubeadm/variables.tf
  kubernetes/onpremise/kubeadm/versions.tf
Labels: infrastructure
