Repository aneoconsulting/ArmoniK.Infra, pull requests merged in 2023-07, with the labels that each got.

#44 refactor: minor fixes on kubeadm deployment scripts
  .gitignore
  kubernetes/onpremise/kubeadm/1-install-master.tf
  kubernetes/onpremise/kubeadm/2-install-workers.tf
  kubernetes/onpremise/kubeadm/README.md
  kubernetes/onpremise/kubeadm/examples/README.md
  kubernetes/onpremise/kubeadm/examples/complete/README.md
  kubernetes/onpremise/kubeadm/examples/complete/main.tf
  kubernetes/onpremise/kubeadm/examples/complete/outputs.tf
  kubernetes/onpremise/kubeadm/examples/complete/terraform.tfvars
  kubernetes/onpremise/kubeadm/examples/complete/variables.tf
  kubernetes/onpremise/kubeadm/examples/complete/versions.tf
  kubernetes/onpremise/kubeadm/exemples/complete/README.md
  kubernetes/onpremise/kubeadm/exemples/complete/main.tf
  kubernetes/onpremise/kubeadm/exemples/complete/outputs.tf
  kubernetes/onpremise/kubeadm/exemples/complete/variables.tf
  kubernetes/onpremise/kubeadm/scripts/install_kubernetes.sh
  kubernetes/onpremise/kubeadm/variables.tf
Labels: infrastructure

#49 fix: Set serve_from_sub_path to false in Grafana
  CHANGELOG.md
  monitoring/onpremise/grafana/init-configmap.tf
Labels: bug

#47 refactor: Update AWS ECR module
  .github/workflows/documentation.yml
  .github/workflows/pre-commit.yml
  CHANGELOG.md
  container-registry/aws/ecr/README.md
  container-registry/aws/ecr/examples/complete/README.md
  container-registry/aws/ecr/examples/complete/main.tf
  container-registry/aws/ecr/examples/complete/outputs.tf
  container-registry/aws/ecr/examples/complete/variables.tf
  container-registry/aws/ecr/examples/complete/versions.tf
  container-registry/aws/ecr/examples/simple/README.md
  container-registry/aws/ecr/examples/simple/main.tf
  container-registry/aws/ecr/examples/simple/outputs.tf
  container-registry/aws/ecr/examples/simple/variables.tf
  container-registry/aws/ecr/examples/simple/versions.tf
  container-registry/aws/ecr/locals.tf
  container-registry/aws/ecr/main.tf
  container-registry/aws/ecr/outputs.tf
  container-registry/aws/ecr/variables.tf
  container-registry/aws/ecr/versions.tf
Labels: enhancement

#51 docs: Autogenerate Helm charts documentations
  .github/workflows/documentation.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  charts/README.md.gotmpl
  charts/eniconfig/Chart.yaml
  charts/eniconfig/values.yaml
  charts/keda-hpa/Chart.yaml
  charts/keda-hpa/values.yaml
Labels: ci

#58 refactor: Add the name of the EKS in the output of VPC
  charts/eniconfig/README.md
  charts/keda-hpa/README.md
  networking/aws/vpc/README.md
  networking/aws/vpc/examples/complete/main.tf
  networking/aws/vpc/main.tf
  networking/aws/vpc/outputs.tf
  networking/aws/vpc/variables.tf
Labels: enhancement

#61 ci: Update CI for Infra modules
  .github/workflows/documentation.yml
  .github/workflows/helm-ci.yml
  .github/workflows/pr-title.yml
  .github/workflows/pre-commit.yml
Labels: ci
